# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teach', models.IntegerField()),
                ('learn', models.IntegerField()),
                ('topic', models.CharField(max_length=30)),
                ('byTime', models.BooleanField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=40)),
                ('password', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PendingTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherId', models.IntegerField()),
                ('learnerId', models.IntegerField()),
                ('skillId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('skillID', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skillID', models.IntegerField(primary_key=True, serialize=False)),
                ('skillName', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=40)),
                ('status', models.CharField(default='', max_length=80)),
                ('location', models.CharField(default='', max_length=40)),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
