# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dobby', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
