# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dobby', '0002_auto_20170325_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedtransaction',
            old_name='learn',
            new_name='learnerId',
        ),
        migrations.RenameField(
            model_name='completedtransaction',
            old_name='topic',
            new_name='skillID',
        ),
        migrations.RenameField(
            model_name='completedtransaction',
            old_name='teach',
            new_name='teacherId',
        ),
    ]
