# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobby', '0004_auto_20170325_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('skillID', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
