# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dobby', '0005_auto_20170326_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedtransaction',
            old_name='skillID',
            new_name='skillId',
        ),
        migrations.RenameField(
            model_name='userskill',
            old_name='skillID',
            new_name='skillId',
        ),
    ]
