# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dobby', '0006_auto_20170326_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingtransaction',
            name='id',
        ),
        migrations.AddField(
            model_name='pendingtransaction',
            name='transId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
