# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dobby', '0008_auto_20170326_0138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OngoingTransaction',
        ),
    ]
