# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dobby', '0012_auto_20170326_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtransaction',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ongoingtransaction',
            name='id',
        ),
        migrations.AddField(
            model_name='completedtransaction',
            name='compId',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ongoingtransaction',
            name='ongId',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
